# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Azure Resources Only
# See readme file for info about the contents of the variable group
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ------------------------------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEV
      - QA
      - PROD
    default: DEV
  # - name: createResourceGroup
  #   displayName: Create Resource Group?
  #   type: boolean
  #   default: true
  # - name: publicAccessEnabled
  #   displayName: Public Access Enabled?
  #   type: boolean
  #   default: true
  # - name: createDnsZones
  #   displayName: Create DNS Zones?
  #   type: boolean
  #   default: true
  # - name: addRoleAssignments
  #   displayName: Add Role Assignments?
  #   type: boolean
  #   default: true
  # - name: apps
  #   displayName: Which Apps to build and deploy?
  #   type: string
  #   values:
  #     - API
  #     - BATCH
  #     - API-BATCH
  #   default: 'API-BATCH'
  - name: buildApps
    displayName: Build Docker Images
    type: boolean
    default: true
  - name: pushApps
    displayName: Push Images to ACR
    type: boolean
    default: true
  - name: deployApps
    displayName: Deploy from ACR to CA
    type: boolean
    default: true
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan?
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.Doc.Review.Keys
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- stage: ScanApplication
  displayName: Scan Application
  jobs:
    - template: pipes/templates/scan-code-template.yml
      parameters:
        environmentName: 'DEV'
        runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
        runGHASScan: false

# ----------------------------------------------------------------------------------------------------
- template: pipes/infra-only-pipe.yml
  parameters:
    environments: ['${{ parameters.deployToEnvironment }}']
    singleEnvironment: 'true'
    createResourceGroup: false
    publicAccessEnabled: true
    createDnsZones: false
    addRoleAssignments: false
    runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
    runGHASScan: false

# ----------------------------------------------------------------------------------------------------
- template: pipes/aca-build-one-pipe.yml
  parameters:
    environmentName: '${{ parameters.deployToEnvironment }}'
    pushToACR: ${{ parameters.pushApps }}
    app: 
      { containerAppName: 'ui', acrAppName: 'assistantui', projectFolderName: 'app/Assistant.UI', port: '8080' }

# ----------------------------------------------------------------------------------------------------
- ${{ if eq(parameters.deployApps, true) }}:
  - template: pipes/aca-deploy-pipe.yml
    parameters:
      environments: ['${{ parameters.deployToEnvironment }}']
      apps: [ 
        { containerAppName: 'ui', acrAppName: 'assistantui', projectFolderName: 'app/Assistant.UI', port: '8080' }
      ] 
