# ----------------------------------------------------------------------------------------------------
# Pipeline to build and deploy one Container App Module
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'
# ----------------------------------------------------------------------------------------------------
trigger: none

# ----------------------------------------------------------------------------------------------------
parameters:
- name: buildApps
  displayName: Build Docker Image
  type: boolean
  default: true
- name: pushApps
  displayName: Push Image to ACR
  type: boolean
  default: true
- name: deployApps
  displayName: Deploy from ACR to CA
  type: boolean
  default: true
- name: runMSDevSecOpsScan
  displayName: Run Scan
  type: boolean
  default: false
# - name: dockerPushType
#   displayName: Docker Build Type
#   type: string
#   values:
#     - native
#     - task
#   default: 'native'

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.Doc.Review.Keys
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if parameters.runMSDevSecOpsScan }}:
    - stage: ScanApplication
      displayName: Scan Application
      jobs:
        - template: pipes/templates/scan-code-template.yml
          parameters:
            environmentName: 'DEV'
            runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
            runGHASScan: false

# ----------------------------------------------------------------------------------------------------
- template: pipes/aca-build-one-pipe.yml
  parameters:
    pushToACR: ${{ parameters.pushApps }}
    apps: [ 
      { containerAppName: 'ui', acrAppName: 'smartflowui', projectFolderName: 'app/SmartFlowUI', port: '8080', acrFolderName: 'smartflow' }
    ] 
    # dockerPushType: ${{ parameters.dockerPushType }}

# ----------------------------------------------------------------------------------------------------
- template: pipes/aca-deploy-pipe.yml
  parameters:
    apps: [ 
      { containerAppName: 'ui', acrAppName: 'smartflowui', projectFolderName: 'app/SmartFlowUI', port: '8080', acrFolderName: 'smartflow' }
    ] 
