# ----------------------------------------------------------------------------------------------------
# Pipeline to scan/build an app upon Pull Request
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
# FYI - Set a required branch policy to run this on every check to main
# ----------------------------------------------------------------------------------------------------
# trigger:
#   - none
pr:
  - main

# ----------------------------------------------------------------------------------------------------
variables:
  - group: AI.Doc.Review.Keys
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
  - template: pipes/aca-build-one-pipe.yml
    parameters:
      pushToACR: false
      app: { containerAppName: 'ui', acrAppName: 'smartflowui', projectFolderName: 'app/SmartFlowUI', port: '8080', acrFolderName: 'smartflow' }

  - template: pipes/scan-code-pipe.yml
    parameters:
      runMSDevSecOpsScan: true
      runGHASScan: false

