# ----------------------------------------------------------------------------------------------------
# Pipe to build an Azure Container App for multiple apps and environments
# ----------------------------------------------------------------------------------------------------
parameters:
  - name: environmentName
    type: string
    default: 'DEV'
  - name: app
    type: object
    default: {}
  - name: pushToACR
    default: true
    type: boolean

# ----------------------------------------------------------------------------------------------------
stages:
- stage: Build${{ parameters.app.containerAppName }}${{ parameters.environmentName }}Service
  displayName: Build ${{ parameters.app.containerAppName }} ${{ parameters.environmentName }}
  jobs:
    - template: templates/aca-build-one-template.yml
      parameters:
        serviceConnectionName: $(serviceConnectionName)
        acrAppName: ${{ parameters.app.acrAppName }}
        projectFolderName: ${{ parameters.app.projectFolderName }}
        environmentName: ${{ parameters.environmentName }}
        pushToACR: ${{ parameters.pushToACR }}
