# ------------------------------------------------------------------------------------------------------------------------
# Action: Deploy Azure Resources via Bicep Files
# ------------------------------------------------------------------------------------------------------------------------
name: 2a - Deploy UI Infrastructure
run-name: 2a - Deploy UI Infrastructure to ENV ${{ inputs.deployEnvironment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod
          - lyle
          - scott
          - piotr
          - chris
          - nick
          - matt
      parameterFile:
        description: 'Parameter File'
        required: true
        default: 'main.gh.bicepparam'
      backendExists:
        description: Does Container Image Exist?
        type: boolean
        default: true
      deploymentMode:
        description: 'Bicep Deploy Mode'
        required: true
        default: 'dev'
        type: choice
        options:
          - Incremental
          - Validation
          - Complete
            
jobs:
  Deploy_Bicep:
    name: Deploy ${{ inputs.deployEnvironment }} Bicep
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
      actions: read
      pages: write
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/bicep/'
      templateFile: 'main.bicep'
      parameterFile: ${{ inputs.parameterFile }}
      parameterFileReplaceTokens: 'true'
      backendExists: ${{ inputs.backendExists }}
      deploymentMode: ${{ inputs.deploymentMode }}
      createResourceGroup: false # ${{ inputs.createResourceGroup }}
      publicAccessEnabled: false # ${{ inputs.publicAccessEnabled }}
      createDnsZones: false # ${{ inputs.createDnsZones }}
      addRoleAssignments: false # ${{ inputs.addRoleAssignments }}
