# ------------------------------------------------------------------------------------------------------------------------
# Action: Scan Bicep and other Source Code on a schedule
# ------------------------------------------------------------------------------------------------------------------------
name: 4 - Scheduled DevOps Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 1 * *" # 1st of Every Month at 1AM
    # - cron: "27 3 * * 1" Every Wednesday at 1AM

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    permissions:
      actions: read
      contents: write
      checks: write
      security-events: write
    with:
      runSecurityScan: true
      continueOnScanError: false
